## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np                #coll library numpy and shortcut np
A=np.random.randint(1,100,[3,3])  #Create an array
B=np.random.randint(1,100,[3,3])  #Create an array

In [4]:
np.dot(A,B)                       #A multiplication B

array([[ 9478,  4720,  7388],
       [12941,  5867,  9902],
       [16378, 10834, 13603]])

## Write a NumPy program to compute the determinant of a given square array

In [6]:
########################من علي النت علشان مشعارفها خالص 

from numpy import linalg as LA     # library linalg shortcut LA
a = np.array([[1, 0], [1, 2]])     #  square array

print(np.linalg.det(a))            # determinant it


2.0


## Write a NumPy program to compute the cross product of two given vectors

In [12]:
print("cross product of the said two vectors(A, B):") #  print a cross b
print(np.cross(A,B))  # function A cross B
print("cross product of the said two vectors(B, A):") #  print a cross b
print(np.cross(B,A))  # function B cross A


cross product of the said two vectors(A, B):
[[ 1676    64 -2582]
 [-1104 -2238  3816]
 [ 3444  2128 -5936]]
cross product of the said two vectors(B, A):
[[-1676   -64  2582]
 [ 1104  2238 -3816]
 [-3444 -2128  5936]]


## Write a NumPy program to compute the condition number of a given matrix

In [13]:
LA.cond(A)  #NumPy function condition 

171.10553959275626

## Write a NumPy program to compute the inverse of a given matrix

In [14]:
np.linalg.inv(A)  #NumPy function inverse

array([[ 0.2613769 , -0.13185531, -0.042007  ],
       [ 0.39731622, -0.24581875, -0.0311163 ],
       [-0.78296383,  0.45896538,  0.09607157]])